# Path to your oh-my-zsh configuration.
export ZSH=$HOME/dev/dotfiles/bash/oh-my-zsh
source ~/dev/dotfiles/bash/environment
source ~/dev/dotfiles/bash/aliases

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="robbyrussell"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

source $ZSH/oh-my-zsh.sh
